package sk.stu.fiit.view.dialogs;

import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import sk.stu.fiit.model.Izba;

/**
 *
 * @author Martin Melisek
 */
public class GaleriaIzbyDialog extends javax.swing.JDialog {

    private Izba zvolenaIzba;
    private JLabel[] obrazky;

    public GaleriaIzbyDialog(java.awt.Frame parent, boolean modal, Izba zvolenaIzba) {
        super(parent, modal);
        initComponents();
        this.obrazky = new JLabel[]{
            obrazok1, obrazok2, obrazok3
        };
        this.zvolenaIzba = zvolenaIzba;
        this.nacitajGaleriu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obrazok1 = new javax.swing.JLabel();
        btnZavriet = new javax.swing.JButton();
        obrazok2 = new javax.swing.JLabel();
        obrazok3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Galeria");
        setPreferredSize(new java.awt.Dimension(905, 501));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        obrazok1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        obrazok1.setText("jLabel2");
        obrazok1.setPreferredSize(new java.awt.Dimension(384, 216));
        getContentPane().add(obrazok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        btnZavriet.setBackground(new java.awt.Color(102, 102, 255));
        btnZavriet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnZavriet.setForeground(new java.awt.Color(255, 255, 255));
        btnZavriet.setText("Zavrieť");
        btnZavriet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnZavrietMouseReleased(evt);
            }
        });
        getContentPane().add(btnZavriet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        obrazok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        obrazok2.setText("jLabel2");
        obrazok2.setPreferredSize(new java.awt.Dimension(384, 216));
        getContentPane().add(obrazok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        obrazok3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        obrazok3.setText("jLabel2");
        obrazok3.setPreferredSize(new java.awt.Dimension(384, 216));
        getContentPane().add(obrazok3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZavrietMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZavrietMouseReleased
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnZavrietMouseReleased

    private void nacitajGaleriu() {
        if (zvolenaIzba.getGaleria().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tato izba nema ziadne fotky v galerii");
            this.setVisible(false);
            this.dispose();
        }
        int idx = 0;
        for (Icon icon : this.zvolenaIzba.getGaleria()) {
            if(idx > 2){
                return;
            }
            this.obrazky[idx].setIcon(icon);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZavriet;
    private javax.swing.JLabel obrazok1;
    private javax.swing.JLabel obrazok2;
    private javax.swing.JLabel obrazok3;
    // End of variables declaration//GEN-END:variables
}
