package sk.stu.fiit.view.panes;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import sk.stu.fiit.database.Database;
import sk.stu.fiit.utils.ViewUtils;
import sk.stu.fiit.view.IViewRefresh;
import sk.stu.fiit.view.MainScreen;
import sk.stu.fiit.view.dialogs.IOManagerDialog;

/**
 *
 * @author Martin Melisek
 */
public class DomovPane extends javax.swing.JPanel implements IViewRefresh {

    public DomovPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnIO = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Štatistiky");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 177, -1, -1));

        jButton1.setText("Nastavenie času");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        jButton2.setText("Nastavenie Jazyka");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        btnIO.setText("Načítavanie a ukladanie údajov...");
        btnIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnIOMouseReleased(evt);
            }
        });
        add(btnIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 290, 130, 22));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        MainScreen parent = (MainScreen) SwingUtilities.getAncestorOfClass(MainScreen.class, this);
        Date d = jDateChooser2.getDate();
        parent.timeSetup(d);
    }//GEN-LAST:event_jButton1MouseReleased

    private void btnIOMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIOMouseReleased
        ViewUtils.showDialog(new IOManagerDialog((JFrame) SwingUtilities.getWindowAncestor(this), true));
        MainScreen parent = (MainScreen) SwingUtilities.getAncestorOfClass(MainScreen.class, this);
        parent.timeSetup(Database.getInstance().getAppTime());
    }//GEN-LAST:event_btnIOMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refreshPane() {
        System.out.println("TATO METODA NIEJE IMPLEMENTOVANA"); //TODO
    }

}
